### ISSUE TITLE
Gazebo models not visible.

### ISSUE THREAD

**Issue by nxmishh** [maker-ATOM/SPARK-A-4DOF-ROS-ROBOTIC-ARM#1]
When I run `gazebo.launch` file the robot model does spawn but gazebo models are not visible, particularly the table, box and the checkered grid. Forward and Inverse Kinematics do work as expected.

Bellow is the image for reference.

![Screenshot from 2023-03-13 23-35-05](https://user-images.githubusercontent.com/113601981/224795820-49381494-b38b-4ec2-8a5c-d149caa88f09.png)

**Comment by maker-ATOM** [comment]
Check the contents of your `.gazebo/models` directory, this is a hidden directory in Home.
If the `models` directory is empty, clone https://github.com/osrf/gazebo_models into `models` and relaunch the `gazebo.launch`.

**Comment by nxmishh** [comment]
Thank you, the issue has been resolved.
